### ISSUE TITLE
Forest Textures

### ISSUE THREAD

**Issue by xackery** [xackery/mp#13]
Create an assortment of forest textures for @alimalkhalifa  and myself
He can put details later on what dimensions and requirements he wants, but it'll be low res stuff. You can browse the github repo's /src/textures dir for some inspiration of what sort of textures will be used.

He has a tree "bark" texture he tossed in, but things to think would be like:

- mossy rock
- lichen base of tree
- dirt trail
- grassy textures

**Comment by Vitoria90** [comment]
I'm going to set up some low res seamless textures of those things, then later we can use those to texture the assets and bake the textures.

**Comment by Vitoria90** [comment]
I've created a handful of forest/nature based textures as, well as setting up a folder just for those base textures.
