### ISSUE TITLE
stone obelisk

### ISSUE THREAD

**Issue by xackery** [xackery/mp#18]
based on https://github.com/xackery/mp/wiki/Small-Pool-(Hub)#stone-obelisks

**Comment by xackery** [comment]
![image](https://user-images.githubusercontent.com/845670/88468945-d6f93680-ce9f-11ea-9dba-ddac71d15e6e.png)

**Comment by xackery** [comment]
@alimalkhalifa what do you think? texture can be revamped once we set theme

**Comment by alimalkhalifa** [comment]
I like it! Textures need to be a tiny bit darker imo. I totally would use the same texture (after making it a grade darker) for all rocks

**Comment by xackery** [comment]
ok, i'm going to toss a darkende version here. You can tell me if it looks good, and/or we can criticize before we push it to repo.
original:
![obelisk](https://user-images.githubusercontent.com/845670/89108015-17017180-d3ea-11ea-9aad-ce1d7ffeb5a3.png)
quick darkened:
![obelisk2](https://user-images.githubusercontent.com/845670/89108021-1d8fe900-d3ea-11ea-8ed5-7f793effb0fd.png)

we can tweak this in other ways if needed, or vary it. Just let me know what direction you'd like to go.

**Comment by alimalkhalifa** [comment]
Let us consider this one done
